name: Collect arXiv daily information


on: 
  schedule:
    - cron:  '1 */8 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[build]')
            || contains(github.event.head_commit.message, '[all]')
            || github.event_name == 'schedule'"

    steps:
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.action }}
    - name: Set up Python 3.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade git+https://github.com/Lyken17/Echoo.git
    - name: Collect information
      run: |
        python arxiv_daily_statistics.py
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Github action automatic update on $(date  +"%m-%d-%Y %H:%M:%S %Z")." -a
        git push 
#     - name: Push changes
#       uses: ad-m/github-push-action@master
#       with:
#         github_token: ${{ secrets.action }}
    - name: Notify Telegram
      run: |
        date_format=$(date +"%y-%b/%-d")
        paper_count=$(cat info/$date_format/paper_counts.txt)
        echoo "arXiv has $paper_count papers on $(date  +"%m-%d-%Y %H:%M:%S %Z")" -t ${{ secrets.tg_token }} -id ${{ secrets.tg_chat_id }}

  watch_keywords:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[build]')
            || contains(github.event.head_commit.message, '[all]')
            || github.event_name == 'schedule'"

    steps:
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.action }}
    - name: Set up Python 3.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade git+https://github.com/Lyken17/Echoo.git
    - name: Watch list
      run: |
        python key_words_trend_track.py --tg_token ${{ secrets.tg_token }} --tg_chat_id ${{ secrets.tg_chat_id }}
